[package]
name = "Exercise05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_lp = { version = "*", features = ["coin_cbc"], default-features = false }
itertools = "0.9"